kind: ServiceAccount
apiVersion: v1
metadata:
  name: curl
---
kind: Pod
apiVersion: v1
metadata:
  name: curl
spec:
  serviceAccountName: curl
  containers:
    - name: curl
      image: curlimages/curl:latest
      command: ["sleep"]
      args: ["infinity"]
